import type { AuditConfidence, AuditFinding, RemediationEffort } from '@shared/types.js'
import { type AuditContext, isElectron } from './context.js'
import { codeFrame, locate, redactAll, snippet } from './lexer.js'
import { computeFingerprint } from './fingerprint.js'
import type { ScanFile } from './context.js'

/** Safety rules appended to every fix prompt so the AI can't "fix" one thing by breaking another. */
const COMMON_SAFETY = [
  'Do not print, log, echo, or commit any secret values, tokens, API keys, passwords, or connection strings.',
  'Do not expose environment variables, cookies, localStorage, sessionStorage, or full user file paths.',
  'Do not weaken or disable any existing security control to make the fix easier.',
  'Validate and sanitize all untrusted input; never build SQL/queries by string concatenation.',
  'Do not send any data to a third-party server as part of this change.',
  'Keep the change minimal and scoped to this single issue.'
]

/** Extra rules that only apply to Electron projects (detected from the project framework). */
const ELECTRON_SAFETY = [
  'Keep contextIsolation: true and nodeIntegration: false.',
  'Keep sandbox: true if my app already uses it.',
  'Do not use innerHTML with untrusted data — use textContent or safe DOM node creation.',
  'Do not add eval, the Function constructor, remote code loading, or unsafe inline script execution.'
]

export function safetyBlock(ctx: AuditContext, extra: string[] = []): string {
  const lines = [...COMMON_SAFETY, ...(isElectron(ctx) ? ELECTRON_SAFETY : []), ...extra]
  return lines.map((l) => `* ${l}`).join('\n')
}

interface ContextHeaderInput {
  id: string
  severity: AuditFinding['severity']
  confidence: AuditConfidence
  category: AuditFinding['category']
  cwe?: string
  references?: string[]
  file?: string
  line?: number
  column?: number
  frame?: string
}

/** Renders the structured finding header that anchors the LLM to the exact location and standard. */
function buildContextHeader(o: ContextHeaderInput): string {
  const lines: string[] = [`--- Security finding ${o.id} ---`]
  lines.push(`Severity: ${o.severity.toUpperCase()} (confidence: ${o.confidence})`)
  lines.push(`Category: ${o.category}`)
  if (o.cwe) lines.push(`Weakness: ${o.cwe}`)
  if (o.references && o.references.length > 0) lines.push(`Standards: ${o.references.join('; ')}`)
  if (o.file) lines.push(`File: ${o.file}`)
  if (o.line) lines.push(`Location: line ${o.line}${o.column ? `, column ${o.column}` : ''}`)
  if (o.frame) {
    lines.push('Code:')
    lines.push(o.frame)
  }
  return lines.join('\n')
}

interface FixSpec {
  ctx: AuditContext
  task: string
  where: string
  problem: string
  goal: string
  steps?: string[]
  extraSafety?: string[]
  /** Structured finding header injected near the top so the model has exact context. */
  context?: string
}

/**
 * Builds a long, structured, copy-paste fix prompt: finding context → task → where → problem →
 * goal → explicit steps → safety requirements → a strict "before/after editing" protocol. This is
 * the direct LLM context the user pastes so the AI fixes the real issue without weakening anything.
 */
export function buildFixPrompt(s: FixSpec): string {
  const parts: string[] = [`You are a senior application-security engineer working inside ${s.ctx.label}.`]
  if (s.context) {
    parts.push(
      '',
      'Finding context (auto-generated by VibeBar\u2019s security audit \u2014 treat the location and code below as ground truth):',
      s.context
    )
  }
  parts.push(
    '',
    `Task: ${s.task}`,
    '',
    'Where:',
    s.where,
    '',
    'Problem:',
    s.problem,
    '',
    'Goal:',
    s.goal
  )
  if (s.steps && s.steps.length > 0) {
    parts.push('', 'Do this:', ...s.steps.map((x, i) => `${i + 1}. ${x}`))
  }
  parts.push(
    '',
    'Safety requirements:',
    safetyBlock(s.ctx, s.extraSafety),
    '',
    'Before editing:',
    '* Open the file and confirm the finding at the line above is real (not a false positive); if it is a false positive, explain why and stop.',
    '* Tell me exactly which file(s) you are changing.',
    '* For every change, show the existing block, the replacement block, and why the change is safe.',
    '* Do not add new dependencies without telling me why and what they do.',
    '',
    'After editing:',
    '* Explain the root cause in plain language first, then give me the minimal fix.',
    '* Confirm you did not weaken any other security control.',
    '* Confirm no secrets, tokens, or full file paths appear in your answer.',
    '* Tell me how to verify the fix manually, then run the behavioral test below to prove it.'
  )
  return parts.join('\n')
}

interface TestSpec {
  ctx: AuditContext
  objective: string
  steps: string[]
  extra?: string[]
}

/** Builds a structured behavioral-test prompt — the runtime proof a static scanner can't give. */
export function buildTestPrompt(s: TestSpec): string {
  const parts: string[] = [
    `You are writing an automated security regression test for ${s.ctx.label} using ${s.ctx.testRunner}.`,
    '',
    'Objective:',
    s.objective,
    '',
    'Write the test so that:',
    ...s.steps.map((x, i) => `${i + 1}. ${x}`),
    '',
    'Important:',
    '* Drive the API/app directly with raw requests, not through the UI — UI tests inherit the frontend\u2019s assumptions.',
    '* The test must FAIL today if the vulnerability is present and PASS once it is fixed.',
    '* Add the test to the suite so it runs on every deploy/CI run.'
  ]
  if (s.extra && s.extra.length > 0) parts.push(...s.extra.map((l) => `* ${l}`))
  return parts.join('\n')
}

// ---------------------------------------------------------------------------
// Finding builders — one for file-anchored findings (with a code frame) and one
// for project-level findings (no single line). Both inject the rich context
// header into the fix prompt and copy the location/standards onto the finding.
// ---------------------------------------------------------------------------

export interface FileFindingSpec {
  input: { ctx: AuditContext }
  file: ScanFile
  index: number
  id: string
  category: AuditFinding['category']
  severity: AuditFinding['severity']
  confidence?: AuditConfidence
  remediationEffort?: RemediationEffort
  cwe?: string
  references?: string[]
  title: string
  detail: string
  /** Secret values to redact from the code frame, evidence, and embedded prompt context. */
  redact?: string[]
  fix: Omit<FixSpec, 'ctx' | 'context'>
  test: Omit<TestSpec, 'ctx'>
}

export function fileFinding(s: FileFindingSpec): AuditFinding {
  const { line, column } = locate(s.file.content, s.index)
  const redact = s.redact ?? []
  const frame = redactAll(codeFrame(s.file.content, s.index), redact)
  const evidence = redactAll(snippet(s.file.content, s.index), redact)
  const confidence: AuditConfidence = s.confidence ?? 'medium'
  const header = buildContextHeader({
    id: s.id,
    severity: s.severity,
    confidence,
    category: s.category,
    cwe: s.cwe,
    references: s.references,
    file: s.file.path,
    line,
    column,
    frame
  })
  return {
    id: s.id,
    category: s.category,
    severity: s.severity,
    confidence,
    title: s.title,
    detail: s.detail,
    file: s.file.path,
    line,
    column,
    codeContext: frame,
    cwe: s.cwe,
    references: s.references,
    evidence,
    fingerprint: computeFingerprint({ ruleId: s.id.split('-')[0] ?? s.id, file: s.file.path, code: evidence }),
    remediationEffort: s.remediationEffort,
    fixPrompt: buildFixPrompt({ ...s.fix, ctx: s.input.ctx, context: header }),
    testPrompt: buildTestPrompt({ ...s.test, ctx: s.input.ctx })
  }
}

export interface MetaFindingSpec {
  input: { ctx: AuditContext }
  id: string
  category: AuditFinding['category']
  severity: AuditFinding['severity']
  confidence?: AuditConfidence
  remediationEffort?: RemediationEffort
  cwe?: string
  references?: string[]
  title: string
  detail: string
  file?: string
  evidence?: string
  fix: Omit<FixSpec, 'ctx' | 'context'>
  test: Omit<TestSpec, 'ctx'>
}

export function metaFinding(s: MetaFindingSpec): AuditFinding {
  const confidence: AuditConfidence = s.confidence ?? 'medium'
  const header = buildContextHeader({
    id: s.id,
    severity: s.severity,
    confidence,
    category: s.category,
    cwe: s.cwe,
    references: s.references,
    file: s.file
  })
  return {
    id: s.id,
    category: s.category,
    severity: s.severity,
    confidence,
    title: s.title,
    detail: s.detail,
    file: s.file,
    cwe: s.cwe,
    references: s.references,
    evidence: s.evidence,
    fingerprint: computeFingerprint({ ruleId: s.id, file: s.file, code: s.evidence }),
    remediationEffort: s.remediationEffort,
    fixPrompt: buildFixPrompt({ ...s.fix, ctx: s.input.ctx, context: header }),
    testPrompt: buildTestPrompt({ ...s.test, ctx: s.input.ctx })
  }
}
