import { CODESYNC_CHANNELS } from '@vibebar/codesync/api'

/**
 * Single source of truth for every IPC channel. The main process registers handlers only
 * for channels in this map and rejects anything else (see security/validateIpc.ts), so the
 * renderer surface stays small and auditable.
 */
export const CH = {
  overlayGetState: 'overlay:getState',
  overlaySetDock: 'overlay:setDock',
  overlaySetPanel: 'overlay:setPanel',
  overlayResetToolbar: 'overlay:resetToolbar',
  /** Collapse expanded panel shell on all displays (startup / recovery). */
  overlayCollapsePanel: 'overlay:collapsePanel',
  /** Expand the overlay window to the work area while the command palette is open. */
  overlaySetCommandPalette: 'overlay:setCommandPalette',
  /** Marks the sender's toolbar as the active one (last clicked) for hotkey routing. */
  overlaySetActive: 'overlay:setActive',
  /** Renderer → main: toggle Agent Companion drawer (expands window outward from toolbar). */
  overlaySetAgentDrawer: 'overlay:setAgentDrawer',
  /** Renderer → main: user started dragging the toolbar strip (-webkit-app-region: drag). */
  overlayDragBegin: 'overlay:dragBegin',
  /** Renderer → main: user released the toolbar drag; snap to the nearest edge. */
  overlayDragEnd: 'overlay:dragEnd',
  /** Renderer → main: React committed the new dock layout — safe to resize the window. */
  overlayLayoutReady: 'overlay:layoutReady',
  overlayLayout: 'overlay:layout',
  /** Main → renderer: open/close the command palette on this display only. */
  overlayCommandPalette: 'overlay:commandPalette',

  projectSelect: 'project:select',
  projectGet: 'project:get',
  projectChanged: 'project:changed',
  projectListRecents: 'project:listRecents',
  projectOpenRecent: 'project:openRecent',
  projectAddContextFolder: 'project:addContextFolder',
  projectOpenContextFolder: 'project:openContextFolder',
  projectGetAiDocs: 'project:getAiDocs',
  projectAppendAgentsMd: 'project:appendAgentsMd',
  projectGetMemoryDiff: 'project:getMemoryDiff',
  projectGetStackOverrides: 'project:getStackOverrides',
  projectSaveStackOverrides: 'project:saveStackOverrides',
  projectClearStackOverrides: 'project:clearStackOverrides',

  promptsList: 'prompts:list',
  promptsPreview: 'prompts:preview',
  promptsCopy: 'prompts:copy',
  promptsToggleFavorite: 'prompts:toggleFavorite',
  promptsCreate: 'prompts:create',
  promptsDelete: 'prompts:delete',
  promptsNewDraft: 'prompts:newDraft',
  promptsHistory: 'prompts:history',
  promptsSetGuardrails: 'prompts:setGuardrails',

  scannerScan: 'scanner:scan',
  scannerCopyRedacted: 'scanner:copyRedacted',

  packerTree: 'packer:tree',
  packerPack: 'packer:pack',
  packerPreviewChanged: 'packer:previewChanged',
  packerPackChanged: 'packer:packChanged',
  packerPresetPaths: 'packer:presetPaths',

  clipboardWrite: 'clipboard:write',

  settingsGet: 'settings:get',
  settingsSave: 'settings:save',
  settingsDisplays: 'settings:displays',

  codesyncToggle: 'codesync:toggle',
  codesyncHide: 'codesync:hide',

  // Detached panel windows (popped-out menus). One floating, always-on-top window per panel;
  // toggling also hides it when visible, so the detached window's own close button reuses this.
  panelDetach: 'panel:detach',

  // Smart Terminal
  terminalToggle: 'terminal:toggle',
  terminalRun: 'terminal:run',
  terminalCancel: 'terminal:cancel',
  terminalClear: 'terminal:clear',
  terminalGetState: 'terminal:getState',
  terminalHide: 'terminal:hide',
  terminalIsOpen: 'terminal:isOpen',
  terminalGetHints: 'terminal:getHints',
  // Custom resize: the window is frameless + transparent (no OS resize border on Windows), so
  // the renderer drives resizing from its own edge grips through these channels.
  terminalResizeStart: 'terminal:resizeStart',
  terminalResize: 'terminal:resize',
  terminalFixWithContext: 'terminal:fixWithContext',
  terminalDismissIssue: 'terminal:dismissIssue',
  terminalData: 'terminal:data',
  terminalStatus: 'terminal:status',
  terminalIssues: 'terminal:issues',
  terminalVisibility: 'terminal:visibility',

  // Built-in interactive shell (cmd/PowerShell) inside the Smart Terminal
  shellStart: 'shell:start',
  shellInput: 'shell:input',
  shellSetShell: 'shell:setShell',
  shellStop: 'shell:stop',
  shellProjectCommands: 'shell:projectCommands',
  shellData: 'shell:data',
  shellReady: 'shell:ready',
  shellClosed: 'shell:closed',

  // Security Audit
  auditRun: 'audit:run',
  auditScan: 'audit:scan',
  auditRunInTerminal: 'audit:runInTerminal',
  auditExportSarif: 'audit:exportSarif',
  auditExportMarkdown: 'audit:exportMarkdown',
  auditGetConfig: 'audit:getConfig',
  auditAcceptRisk: 'audit:acceptRisk',
  auditSetRuleDisabled: 'audit:setRuleDisabled',

  // Snip to AI Context — drag-select a screen region, preview, then save it to the AI context
  // folder and hand back a ready-to-paste prompt referencing the image.
  snipStart: 'snip:start',
  snipGetCapture: 'snip:getCapture',
  snipSave: 'snip:save',
  snipCancel: 'snip:cancel',

  // Notes — project-scoped Markdown notes (library + sticky pop-out windows)
  notesGetState: 'notes:getState',
  notesInit: 'notes:init',
  notesCreate: 'notes:create',
  notesRead: 'notes:read',
  notesSave: 'notes:save',
  notesDelete: 'notes:delete',
  notesSetProjectName: 'notes:setProjectName',
  notesPopOut: 'notes:popOut',
  notesAppendMarkdown: 'notes:appendMarkdown',
  notesFindSessionLog: 'notes:findSessionLog',
  notesChanged: 'notes:changed',

  // Session Hub — project-local timeline + handoff bundles
  sessionGetState: 'session:getState',
  sessionAppend: 'session:append',
  sessionTogglePin: 'session:togglePin',
  sessionClear: 'session:clear',
  sessionCopyHandoff: 'session:copyHandoff',
  sessionCopyFixPrompts: 'session:copyFixPrompts',
  sessionSetIntent: 'session:setIntent',
  sessionClearIntent: 'session:clearIntent',
  sessionRerunVerify: 'session:rerunVerify',
  sessionChanged: 'session:changed',

  // GitHub Desktop + live change tracking
  githubOpen: 'github:open',
  githubGetDesktopPath: 'github:getDesktopPath',
  githubSetDesktopPath: 'github:setDesktopPath',
  githubLocateDesktop: 'github:locateDesktop',
  gitStatus: 'git:status',
  gitStatusChanged: 'git:statusChanged',
  gitCopyDiffPrompt: 'git:copyDiffPrompt',
  gitChangedFiles: 'git:changedFiles',

  // Ready Check — pre-commit trust gate (read-only aggregation)
  readyCheckGet: 'readyCheck:get',
  readyCheckCopyReviewPrompt: 'readyCheck:copyReviewPrompt',
  readyCheckCopyUntrackedSummary: 'readyCheck:copyUntrackedSummary',
  readyCheckCopyDependencyReview: 'readyCheck:copyDependencyReview',
  readyCheckCopyRegressionContext: 'readyCheck:copyRegressionContext',

  // In-app error console — a renderer reports a captured (already-redacted) runtime error; the
  // console window receives the live list and asks main to clear/close itself.
  errorsReport: 'errors:report',
  errorsClear: 'errors:clear',
  errorsClose: 'errors:close',
  errorsPush: 'errors:push',

  // System resource widgets — main polls the OS and pushes a snapshot to each floating widget.
  resourcesPush: 'resources:push',

  // Quick Launch — one-click external editor/app launchers (Cursor, Codex, custom)
  quickLaunchList: 'quickLaunch:list',
  quickLaunchRun: 'quickLaunch:run',
  quickLaunchPrepareCursor: 'quickLaunch:prepareCursor',
  quickLaunchAdd: 'quickLaunch:add',
  quickLaunchRemove: 'quickLaunch:remove',
  quickLaunchLocate: 'quickLaunch:locate',
  quickLaunchSetVisible: 'quickLaunch:setVisible',
  quickLaunchChanged: 'quickLaunch:changed',

  /** Optional localhost MCP server for Cursor Agent integration. */
  mcpGetStatus: 'mcp:getStatus',
  mcpChanged: 'mcp:changed',

  /** Agent Companion — ACP chat drawer anchored to Cursor quick launch. */
  agentCompanionGetState: 'agentCompanion:getState',
  agentCompanionToggleDrawer: 'agentCompanion:toggleDrawer',
  agentCompanionSetDrawerOpen: 'agentCompanion:setDrawerOpen',
  agentCompanionConnect: 'agentCompanion:connect',
  agentCompanionDisconnect: 'agentCompanion:disconnect',
  agentCompanionSendPrompt: 'agentCompanion:sendPrompt',
  agentCompanionCancel: 'agentCompanion:cancel',
  agentCompanionSetMode: 'agentCompanion:setMode',
  agentCompanionSetModel: 'agentCompanion:setModel',
  agentCompanionListModels: 'agentCompanion:listModels',
  agentCompanionNewChat: 'agentCompanion:newChat',
  agentCompanionSelectChat: 'agentCompanion:selectChat',
  agentCompanionDeleteChat: 'agentCompanion:deleteChat',
  agentCompanionPickHistoryDir: 'agentCompanion:pickHistoryDir',
  agentCompanionRespondPermission: 'agentCompanion:respondPermission',
  agentCompanionRespondQuestion: 'agentCompanion:respondQuestion',
  agentCompanionSkipQuestion: 'agentCompanion:skipQuestion',
  agentCompanionState: 'agentCompanion:state',

  appQuit: 'app:quit',
  appGetOnboardingState: 'app:getOnboardingState',
  appCompleteOnboarding: 'app:completeOnboarding',
  appShowOnboardingAgain: 'app:showOnboardingAgain',
  // Opens the centered "Close Vibe Bar" confirmation window (power button); cancel hides it.
  appConfirmQuit: 'app:confirmQuit',
  appCancelQuit: 'app:cancelQuit'
} as const

export type ChannelName = (typeof CH)[keyof typeof CH]

/** Channels the renderer is allowed to invoke via ipcRenderer.invoke. */
export const INVOKABLE_CHANNELS: readonly string[] = [
  CH.overlayGetState,
  CH.overlaySetDock,
  CH.overlaySetPanel,
  CH.overlayResetToolbar,
  CH.overlayCollapsePanel,
  CH.overlaySetCommandPalette,
  CH.overlaySetActive,
  CH.overlayDragBegin,
  CH.overlayDragEnd,
  CH.overlayLayoutReady,
  CH.overlaySetAgentDrawer,
  CH.projectSelect,
  CH.projectGet,
  CH.projectListRecents,
  CH.projectOpenRecent,
  CH.projectAddContextFolder,
  CH.projectOpenContextFolder,
  CH.projectGetAiDocs,
  CH.projectAppendAgentsMd,
  CH.projectGetMemoryDiff,
  CH.projectGetStackOverrides,
  CH.projectSaveStackOverrides,
  CH.projectClearStackOverrides,
  CH.promptsList,
  CH.promptsPreview,
  CH.promptsCopy,
  CH.promptsToggleFavorite,
  CH.promptsCreate,
  CH.promptsDelete,
  CH.promptsNewDraft,
  CH.promptsHistory,
  CH.promptsSetGuardrails,
  CH.scannerScan,
  CH.scannerCopyRedacted,
  CH.packerTree,
  CH.packerPack,
  CH.packerPreviewChanged,
  CH.packerPackChanged,
  CH.packerPresetPaths,
  CH.clipboardWrite,
  CH.settingsGet,
  CH.settingsSave,
  CH.settingsDisplays,
  CH.codesyncToggle,
  CH.codesyncHide,
  CH.panelDetach,
  CH.terminalToggle,
  CH.terminalRun,
  CH.terminalCancel,
  CH.terminalClear,
  CH.terminalGetState,
  CH.terminalHide,
  CH.terminalIsOpen,
  CH.terminalGetHints,
  CH.terminalResizeStart,
  CH.terminalResize,
  CH.terminalFixWithContext,
  CH.terminalDismissIssue,
  CH.shellStart,
  CH.shellInput,
  CH.shellSetShell,
  CH.shellStop,
  CH.shellProjectCommands,
  CH.auditRun,
  CH.auditScan,
  CH.auditRunInTerminal,
  CH.auditExportSarif,
  CH.auditExportMarkdown,
  CH.auditGetConfig,
  CH.auditAcceptRisk,
  CH.auditSetRuleDisabled,
  CH.snipStart,
  CH.snipGetCapture,
  CH.snipSave,
  CH.snipCancel,
  CH.notesGetState,
  CH.notesInit,
  CH.notesCreate,
  CH.notesRead,
  CH.notesSave,
  CH.notesDelete,
  CH.notesSetProjectName,
  CH.notesPopOut,
  CH.notesAppendMarkdown,
  CH.notesFindSessionLog,
  CH.githubOpen,
  CH.githubGetDesktopPath,
  CH.githubSetDesktopPath,
  CH.githubLocateDesktop,
  CH.gitStatus,
  CH.gitCopyDiffPrompt,
  CH.gitChangedFiles,
  CH.readyCheckGet,
  CH.readyCheckCopyReviewPrompt,
  CH.readyCheckCopyUntrackedSummary,
  CH.readyCheckCopyDependencyReview,
  CH.readyCheckCopyRegressionContext,
  CH.sessionGetState,
  CH.sessionAppend,
  CH.sessionTogglePin,
  CH.sessionClear,
  CH.sessionCopyHandoff,
  CH.sessionCopyFixPrompts,
  CH.sessionSetIntent,
  CH.sessionClearIntent,
  CH.sessionRerunVerify,
  CH.errorsReport,
  CH.errorsClear,
  CH.errorsClose,
  CH.quickLaunchList,
  CH.quickLaunchRun,
  CH.quickLaunchPrepareCursor,
  CH.quickLaunchAdd,
  CH.quickLaunchRemove,
  CH.quickLaunchLocate,
  CH.quickLaunchSetVisible,
  CH.mcpGetStatus,
  CH.agentCompanionGetState,
  CH.agentCompanionToggleDrawer,
  CH.agentCompanionSetDrawerOpen,
  CH.agentCompanionConnect,
  CH.agentCompanionDisconnect,
  CH.agentCompanionSendPrompt,
  CH.agentCompanionCancel,
  CH.agentCompanionSetMode,
  CH.agentCompanionSetModel,
  CH.agentCompanionListModels,
  CH.agentCompanionNewChat,
  CH.agentCompanionSelectChat,
  CH.agentCompanionDeleteChat,
  CH.agentCompanionPickHistoryDir,
  CH.agentCompanionRespondPermission,
  CH.agentCompanionRespondQuestion,
  CH.agentCompanionSkipQuestion,
  CH.appQuit,
  CH.appGetOnboardingState,
  CH.appCompleteOnboarding,
  CH.appShowOnboardingAgain,
  CH.appConfirmQuit,
  CH.appCancelQuit,
  // Code Sync runs its own IPC registry (packages/codesync) with its own payload validation
  // (validateSyncStart / validateConfigSave). Its invokable channels are mirrored here so this
  // allowlist remains the single, complete record of every channel the renderer can invoke.
  CODESYNC_CHANNELS.pickFolder,
  CODESYNC_CHANNELS.configLoad,
  CODESYNC_CHANNELS.configSave,
  CODESYNC_CHANNELS.syncStart,
  CODESYNC_CHANNELS.syncStop,
  CODESYNC_CHANNELS.syncStatus,
  // The detached Code Sync window hides itself via this dedicated channel (see preload/codesync).
  'codesync:hide'
]

/** Channels the main process pushes to the renderer via webContents.send. */
export const PUSH_CHANNELS: readonly string[] = [
  CH.overlayLayout,
  CH.overlayCommandPalette,
  CH.projectChanged,
  CH.terminalData,
  CH.terminalStatus,
  CH.terminalIssues,
  CH.terminalVisibility,
  CH.shellData,
  CH.shellReady,
  CH.shellClosed,
  CH.gitStatusChanged,
  CH.notesChanged,
  CH.sessionChanged,
  CH.quickLaunchChanged,
  CH.mcpChanged,
  CH.agentCompanionState,
  CH.errorsPush,
  CH.resourcesPush,
  CODESYNC_CHANNELS.log
]
